# Travis auto-virtualenv isn't supported on OS X
language: generic
sudo: required
matrix:
  include:
    - python: 3.4
      language: python
      python: "3.4"
      os: linux
      dist: trusty
      env: PYTHON=/usr/bin/python3.4
    - python: 3
      os: osx
      env: PYTHON=/usr/local/bin/python3 CC=/usr/local/bin/gcc-4.9 CXX=/usr/local/bin/g++-4.9
virtualenv:
  system_site_packages: true
before_install:
  - source .travis.before_install.bash
before_script:
  - source .travis.before_script.bash
script:
  - "python setup.py test"
notifications:
  email:
    - lars.pastewka@kit.edu
addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libfftw3-dev
    - netcdf-dev
    - python-numpy
    - python-scipy
    - python-matplotlib
    - python-tk
    - cython
    - python3-numpy
    - python3-scipy
    - python3-matplotlib
    - python3-tk
    - cython3
