# Travis auto-virtualenv isn't supported on OS X
language: generic
sudo: required
matrix:
  include:
    - python: 3.4
      language: python
      python: "3.4"
      os: linux
      env: PYTHON=/usr/bin/python3.4
    - python: 3
      os: osx
      env: PYTHON=/usr/local/bin/python3 CC=/usr/local/bin/gcc-4.9 CXX=/usr/local/bin/g++-4.9
before_install:
  - source .travis.before_install.bash
before_script:
  - source .travis.before_script.bash
script:
  - "pip list"
  - "python -V"
  - "python setup.py test"
notifications:
  email:
    - lars.pastewka@kit.edu
    - till.junge@epfl.ch
addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - python-numpy
    - python-scipy
    - python-matplotlib
    - cython
