# Travis auto-virtualenv isn't supported on OS X
language: generic
sudo: required
matrix:
  include:
    - python: 2.6
      language: python
      python: "2.6"
      os: linux
      env: PYTHON=/usr/bin/python2.6
    - python: 2.7
      language: python
      python: "2.7"
      os: linux
      env: PYTHON=/usr/bin/python2.7
    - python: 3.4
      language: python
      python: "3.4"
      os: linux
      env: PYTHON=/usr/bin/python3.4
    - python: 2
      os: osx
      env: PYTHON=/usr/bin/python CC=clang CXX=clang++
    - python: 2
      os: osx
      env: PYTHON=/usr/local/bin/python CC=/usr/local/bin/gcc-4.9 CXX=/usr/local/bin/g++-4.9
    - python: 3
      os: osx
      env: PYTHON=/usr/local/bin/python3 CC=/usr/local/bin/gcc-4.9 CXX=/usr/local/bin/g++-4.9
before_install:
  - source .travis.before_install.bash
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
before_script:
  - source .travis.before_script.bash
script:
  - "cd tests ; python run_tests.py"
notifications:
  email:
    - lars.pastewka@kit.edu
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-matplotlib
    - cython